(function(g){var window=this;'use strict';var cub=function(a,b){g.V.call(this,{I:"button",Ma:["ytp-miniplayer-expand-watch-page-button","ytp-button","ytp-miniplayer-button-top-left"],X:{title:"{{title}}","data-tooltip-target-id":"ytp-miniplayer-expand-watch-page-button","aria-keyshortcuts":"i","data-title-no-tooltip":"{{data-title-no-tooltip}}"},V:[{I:"svg",X:{height:"24px",version:"1.1",viewBox:"0 0 24 24",width:"24px"},V:[{I:"g",X:{fill:"none","fill-rule":"evenodd",stroke:"none","stroke-width":"1"},V:[{I:"g",X:{transform:"translate(12.000000, 12.000000) scale(-1, 1) translate(-12.000000, -12.000000) "},
V:[{I:"path",X:{d:"M19,19 L5,19 L5,5 L12,5 L12,3 L5,3 C3.89,3 3,3.9 3,5 L3,19 C3,20.1 3.89,21 5,21 L19,21 C20.1,21 21,20.1 21,19 L21,12 L19,12 L19,19 Z M14,3 L14,5 L17.59,5 L7.76,14.83 L9.17,16.24 L19,6.41 L19,10 L21,10 L21,3 L14,3 Z",fill:"#fff","fill-rule":"nonzero"}}]}]}]}]});this.J=a;this.Ua("click",this.onClick,this);this.updateValue("title",g.aU(a,"\ud655\uc7a5","i"));this.update({"data-title-no-tooltip":"\ud655\uc7a5"});this.addOnDisposeCallback(g.ZT(b.Re(),this.element))},dub=function(a){g.V.call(this,
{I:"div",
S:"ytp-miniplayer-ui"});this.G=!1;this.player=a;this.T(a,"minimized",this.lh);this.T(a,"onStateChange",this.o3)},eub=function(a){g.PV.call(this,a);
this.B=new g.AK(this);this.j=new dub(this.player);this.j.hide();g.iU(this.player,this.j.element,4);a.vg()&&(this.load(),g.lv(a.getRootNode(),"ytp-player-minimized",!0))};
g.x(cub,g.V);cub.prototype.onClick=function(){this.J.qb("onExpandMiniplayer")};g.x(dub,g.V);g.k=dub.prototype;
g.k.show=function(){this.j=new g.Ru(this.m3,null,this);this.j.start();if(!this.G){this.tooltip=new g.aY(this.player,this);g.N(this,this.tooltip);g.iU(this.player,this.tooltip.element,4);this.tooltip.scale=.6;this.le=new g.tW(this.player);g.N(this,this.le);this.B=new g.V({I:"div",S:"ytp-miniplayer-scrim"});g.N(this,this.B);this.B.Ka(this.element);this.T(this.B.element,"click",this.uT);var a=new g.V({I:"button",Ma:["ytp-miniplayer-close-button","ytp-button"],X:{"aria-label":"\ub2eb\uae30"},V:[g.TF()]});
g.N(this,a);a.Ka(this.B.element);this.T(a.element,"click",this.tT);a=new cub(this.player,this);g.N(this,a);a.Ka(this.B.element);this.C=new g.V({I:"div",S:"ytp-miniplayer-controls"});g.N(this,this.C);this.C.Ka(this.B.element);this.T(this.C.element,"click",this.uT);var b=new g.V({I:"div",S:"ytp-miniplayer-button-container"});g.N(this,b);b.Ka(this.C.element);a=new g.V({I:"div",S:"ytp-miniplayer-play-button-container"});g.N(this,a);a.Ka(this.C.element);var c=new g.V({I:"div",S:"ytp-miniplayer-button-container"});
g.N(this,c);c.Ka(this.C.element);this.N=new g.nX(this.player,this,!1);g.N(this,this.N);this.N.Ka(b.element);b=new g.mX(this.player,this);g.N(this,b);b.Ka(a.element);this.nextButton=new g.nX(this.player,this,!0);g.N(this,this.nextButton);this.nextButton.Ka(c.element);this.K=new g.UX(this.player,this);g.N(this,this.K);this.K.Ka(this.B.element);this.progressBar=new g.sX(this.player,this);g.N(this,this.progressBar);g.iU(this.player,this.progressBar.element,4);this.D=new g.V({I:"div",S:"ytp-miniplayer-buttons"});
g.N(this,this.D);g.iU(this.player,this.D.element,4);a=new g.V({I:"button",Ma:["ytp-miniplayer-close-button","ytp-button"],X:{"aria-label":"\ub2eb\uae30"},V:[g.TF()]});g.N(this,a);a.Ka(this.D.element);this.T(a.element,"click",this.tT);a=new g.V({I:"button",Ma:["ytp-miniplayer-replay-button","ytp-button"],X:{"aria-label":"\ub2eb\uae30"},V:[g.cxa()]});g.N(this,a);a.Ka(this.D.element);this.T(a.element,"click",this.vaa);this.T(this.player,"presentingplayerstatechange",this.n3);this.T(this.player,"appresize",
this.Xb);this.T(this.player,"fullscreentoggled",this.Xb);this.Xb();this.G=!0}0!==this.player.getPlayerState()&&g.V.prototype.show.call(this);this.progressBar.show();this.player.unloadModule("annotations_module")};
g.k.hide=function(){this.j&&(this.j.dispose(),this.j=void 0);g.V.prototype.hide.call(this);this.player.vg()||(this.G&&this.progressBar.hide(),this.player.loadModule("annotations_module"))};
g.k.xa=function(){this.j&&(this.j.dispose(),this.j=void 0);g.V.prototype.xa.call(this)};
g.k.tT=function(){this.player.stopVideo();this.player.qb("onCloseMiniplayer")};
g.k.vaa=function(){this.player.playVideo()};
g.k.uT=function(a){if(a.target===this.B.element||a.target===this.C.element)g.uL(this.player.Vb())?this.player.pauseVideo():this.player.playVideo()};
g.k.lh=function(){g.lv(this.player.getRootNode(),"ytp-player-minimized",this.player.vg())};
g.k.fg=function(){this.progressBar.Tc();this.K.Tc()};
g.k.m3=function(){this.fg();this.j&&this.j.start()};
g.k.n3=function(a){g.AG(a.state,32)&&this.tooltip.hide()};
g.k.Xb=function(){g.p1a(this.progressBar,0,this.player.rb().getPlayerSize().width,!1);g.tX(this.progressBar)};
g.k.o3=function(a){this.player.vg()&&(0===a?this.hide():this.show())};
g.k.Re=function(){return this.tooltip};
g.k.Wt=function(a,b,c,d,e){var f=0,h=d=0,l=g.zs(a);if(b){c=g.$u(b,"ytp-prev-button")||g.$u(b,"ytp-next-button");var m=g.$u(b,"ytp-play-button"),n=g.$u(b,"ytp-miniplayer-expand-watch-page-button");c?f=h=12:m?(b=g.xs(b,this.element),h=b.x,f=b.y-12):n&&(h=g.$u(b,"ytp-miniplayer-button-top-left"),f=g.xs(b,this.element),b=g.zs(b),h?(h=8,f=f.y+40):(h=f.x-l.width+b.width,f=f.y-20))}else h=c-l.width/2,d=25+(e||0);b=this.player.rb().getPlayerSize().width;e=f+(e||0);l=g.He(h,0,b-l.width);e?(a.style.top=e+"px",
a.style.bottom=""):(a.style.top="",a.style.bottom=d+"px");a.style.left=l+"px"};g.x(eub,g.PV);g.k=eub.prototype;g.k.onVideoDataChange=function(){if(this.player.getVideoData()){var a=this.player.getVideoAspectRatio(),b=16/9;a=a>b+.1||a<b-.1;g.lv(this.player.getRootNode(),"ytp-rounded-miniplayer-not-regular-wide-video",a)}};
g.k.create=function(){g.PV.prototype.create.call(this);this.B.T(this.player,"videodatachange",this.onVideoDataChange);this.onVideoDataChange()};
g.k.Bl=function(){return!1};
g.k.load=function(){this.player.hideControls();this.j.show()};
g.k.unload=function(){this.player.showControls();this.j.hide()};g.OV("miniplayer",eub);})(_yt_player);
